"use client";

import { useState } from "react";
import { IconChevronDown } from "@tabler/icons-react";

export function Faqs() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const faqs = [
    {
      question: "What is GenasAI?",
      answer: "GenasAI is an intelligent workspace that helps students, educators, and researchers generate, customize, and export high-quality academic content in minutes powered by advanced AI."
    },
    {
      question: "How is GenasAI different from other AI writing tools?",
      answer: "Unlike generic AI writers, GenasAI is specifically trained for academic formats (APA, MLA, etc.), offering customized depth, section controls, and full document history tailored to academic standards."
    },
    {
      question: "Can I choose the format and template of my document?",
      answer: "Yes, you can select specific academic formatting guidelines, custom templates, depth of content, and the number of sections before generating your document."
    },
    {
      question: "Is the content generated by GenasAI original?",
      answer: "GenasAI generates unique content based on your instructions. However, we always recommend reviewing and citing appropriately for academic integrity."
    },
    {
      question: "Can I edit or regenerate specific parts of my document?",
      answer: "Absolutely! The platform allows you to surgically edit or regenerate specific sections without needing to recreate the entire document."
    },
    {
      question: "Can I cancel my subscription anytime?",
      answer: "Yes, you can easily cancel or modify your subscription plan at any time from your account dashboard."
    },
  ];

  return (
    <section className="py-24 bg-[#f8fafc]/50 flex flex-col items-center justify-center px-4 mb-24">
      {/* Header */}
      <div className="max-w-3xl mx-auto mb-16 relative z-10 flex flex-col items-center text-center">
        <div className="inline-flex items-center justify-center bg-white border border-slate-200 text-slate-500 text-[11px] font-semibold px-4 py-1.5 rounded-full mb-6 shadow-sm uppercase tracking-wider">
          FAQS
        </div>
        <h2 className="text-4xl md:text-5xl font-bold text-slate-900 tracking-tight leading-tight max-w-lg">
          Frequently Asked Questions
        </h2>
      </div>

      {/* Accordion */}
      <div className="w-full max-w-3xl mx-auto flex flex-col gap-4">
        {faqs.map((faq, index) => {
          const isOpen = openIndex === index;
          return (
            <div 
              key={index} 
              className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden transition-all duration-300"
            >
              <button
                className="w-full flex items-center justify-between px-6 py-5 text-left bg-transparent cursor-pointer focus:outline-none"
                onClick={() => setOpenIndex(isOpen ? null : index)}
              >
                <span className="text-[17px] font-semibold text-slate-800 pr-8">
                  {faq.question}
                </span>
                <span className={`flex-shrink-0 transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`}>
                  <IconChevronDown className="w-5 h-5 text-slate-500" />
                </span>
              </button>
              
              <div 
                className={`transition-all duration-300 ease-in-out ${isOpen ? 'max-h-48 opacity-100' : 'max-h-0 opacity-0 overflow-hidden'}`}
              >
                 <div className="px-6 pb-6 text-[15px] font-medium text-slate-500 leading-relaxed">
                   {faq.answer}
                 </div>
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
}
